project:
  type: book

book:
  title: "Bayesian Experimentation"
  author: "Miha Gazvoda"
  date: "6/29/2025"
  chapters:
    - index.qmd
    - intro.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt

jupyter: .venv/bin/python

# Python kernel configuration
# execute:
#   echo: true
#   eval: true
#   error: false
#   warning: false
#   include: true
#   cache: true



