[project]
name = "bayesian-experimentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "polars>=1.31.0",
    "pymc>=5.23.0",
]
